// Code generated by mockery v1.0.0
package mocks

import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

// Bind provides a mock function with given fields: server
func (_m *API) Bind(server *grpc.Server) {
	_m.Called(server)
}
